# inspired by https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
name: Build & Push Docker image

on:
  push:
    tags:
      - '*'

jobs:

  build-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Get tag name
        id: get_tag_name
        run: |
          echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          dockerTag=`echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-`
          echo "DOCKER_TAG=$dockerTag" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get_tag_name.outputs.GIT_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/386,linux/mips64le,linux/ppc64le,linux/s390x
          tags: char0n/postgresql-czech-fulltext:${{ steps.get_tag_name.outputs.DOCKER_TAG }}
